### ISSUE TITLE
Use string instead of symbols

### ISSUE THREAD

**Issue by domenic** [rwaldron/enum-definitions#1]
Symbols don't buy us anything here. They're useful as meta-property hooks so people can use methods named "iterator" without accidentally opting in to ES semantics. But let's say your API accepts a color enum. If someone passes in "BLUE", there's no gain in rejecting that, and saying "you must type Color.BLUE". The values should just be strings, with the benefit of the proposal coming from the checking so that `Color.BLU` is caught as a typo.

This also has the benefit of matching existing enums in 402 and the web, which are all strings. (Except some legacy web ones which are integers, from the bad days when people though that the DOM was meant for Java bindings...)

**Comment by rwaldron** [comment]
I have no argument against this, but there has been equal interest in using `Symbol("The Identifier StringValue")`

> This also has the benefit of matching existing enums in 402 and the web, which are all strings

...But this is compelling.

**Comment by jeffmo** [comment]
I like the idea of using symbols over another data type (i.e. strings/numbers) since strings/numbers can collide more easily with other values and symbols allow enums to stay disjoint (i.e. `hex.BLUE` can't be confused with `rgb.BLUE`).

~~Detecting that `Color.BLU` is a typo requires a type system (or some kind of proxy semantics that throw on unexpected property accesses).~~

**EDIT: Just noticed https://github.com/rwaldron/proposal-enum-definitions/issues/2 is a proposed addition: 👍👍**

> This also has the benefit of matching existing enums in 402 and the web, which are all strings

Agree we'd want to find a way to converge here. Would it be possible for these APIs to take both strings and an enum symbol?

**Comment by domenic** [comment]
> Agree we'd want to find a way to converge here. Would it be possible for these APIs to take both strings and an enum symbol?

Why? Strings are just as good. There's no benefit in collision avoidance here. You just need "blue" as a concept; you don't care which enum it came from.

**Comment by jeffmo** [comment]
> You just need "blue" as a concept; you don't care which enum it came from.

In the case of DOM libraries, you probably don't really care which blue between hex and rbg (which is why taking both a string or a symbol would probably work for these libs). The main benefit of supporting both, as you pointed out, is the #2 -feature you get if you use the enum instead.

But in circumstances where the enum itself gets passed around it can be easy to see `e.BLUE` and not realize that `e` is actually an enum of characters from [Old School](http://www.imdb.com/title/tt0302886/) leading to surprise later if you change `setColor(e.BLUE)` to `setColor(e.ORANGE)` and the API suddenly throws. Using Symbol values would let you fail faster in these kinds scenarios and grab/use the proper enum from the get-go.

This is a goofy example, but you can imagine plenty of these scenarios: One library that manages, say, immutable collections (sets/maps/lists/etc) and one that deals with some kind of action (get/set/update/etc).

FWIW: There is some prior art in TypeScript that has an enums which are enforced nominally in this way:

http://www.typescriptlang.org/play/index.html#src=enum%20A%20%7B%0A%09RED%0A%7D%0A%0Aenum%20B%20%7B%0A%09RED%0A%7D%0A%0Aconst%20a%3A%20A%20%3D%20B.RED%3B

**Comment by domenic** [comment]
Sure, these are all reasonable things for a type checker to enforce. They aren't justification for making the web platform APIs mint and accept redundant symbol values, however.

**Comment by jeffmo** [comment]
To be clear: I don't think anything here really requires web platform APIs to accept the symbol values (there are plenty of APIs that simply pre-date features they might've used if they'd been designed after the feature existed), I just thought it would be nice if they did support it for all the same reasons you stated

**Comment by rwaldron** [comment]
Presently, everything in this repo is out of date, so please don't bother commenting on it. We've been working on a way to provide a mechanism that allows the values to be user-code definable, with intuitive defaults. Thanks
